
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 12 10:19:05 PST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 27;
  public static final int MENOS = 3;
  public static final int LT = 21;
  public static final int IDENT = 29;
  public static final int ELSE = 13;
  public static final int CP = 9;
  public static final int PYC = 17;
  public static final int OR = 26;
  public static final int EQUAL = 19;
  public static final int NOTEQUAL = 20;
  public static final int CL = 11;
  public static final int WHILE = 14;
  public static final int NOT = 25;
  public static final int IF = 12;
  public static final int GT = 23;
  public static final int LE = 22;
  public static final int POR = 4;
  public static final int AP = 8;
  public static final int DO = 15;
  public static final int AL = 10;
  public static final int MENOSUNARIO = 6;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int GE = 24;
  public static final int MASMAS = 7;
  public static final int NUMERO = 30;
  public static final int PRINT = 28;
  public static final int error = 1;
  public static final int FOR = 16;
  public static final int ASIG = 18;
  public static final int MAS = 2;
}

